name = "my-backend"
version = "0.1.0"
dependencies = [
"fastapi>=0.115",
"uvicorn[standard]>=0.30",
"sqlmodel>=0.0.21",
"sqlalchemy>=2.0",
"pydantic-settings>=2.4",
"python-dotenv>=1.0"
]
[tool.uvicorn]
reload = true
host = "127.0.0.1"
port = 8000
