# backend/app/taxa_timbru_data.py
# -*- coding: utf-8 -*-
"""
Definește constantele și structura de date centrală (TIPURI_CERERI)
pentru calculul taxei judiciare de timbru conform OUG 80/2013.
Lista TIPURI_CERERI a fost extinsă pentru a include regulile de calcul
menționate în OUG 80/2013 și în logica din taxa_timbru_logic.py.
Cuvintele cheie și numele standard pot fi acum încărcate parțial din ../../public/variabile.json.
"""
import json
import os
import logging
from typing import List, Dict, Any, Optional, Union

# Configurare logger
logger = logging.getLogger(__name__)

# ============================================
# Încărcare variabile externe (keywords și nume_standard)
# ============================================
variabile_data = {}
taxa_timbru_keywords = {}
taxa_timbru_nume_standard_json = {} # Nou: pentru nume_standard din JSON

try:
    # Determinare cale absolută relativ la acest fișier
    current_dir = os.path.dirname(os.path.abspath(__file__))
    # Cale relativă: din backend/app/ mergem două niveluri sus (..) apoi în public/
    json_file_path = os.path.normpath(os.path.join(current_dir, '..', 'data', 'variabile.json'))

    if os.path.exists(json_file_path):
        with open(json_file_path, 'r', encoding='utf-8') as f:
            variabile_data = json.load(f)
        taxa_timbru_keywords = variabile_data.get("taxaTimbruKeywords", {})
        taxa_timbru_nume_standard_json = variabile_data.get("taxaTimbruNumeStandard", {}) # Nou

        if not taxa_timbru_keywords:
             logger.warning(f"Secțiunea 'taxaTimbruKeywords' nu a fost găsită sau este goală în {json_file_path}")
        if not taxa_timbru_nume_standard_json:
             logger.warning(f"Secțiunea 'taxaTimbruNumeStandard' nu a fost găsită sau este goală în {json_file_path}. Se vor folosi valorile 'nume_standard' hardcodate în Python.")
        # logger.info(f"Fișierul variabile.json încărcat cu succes din {json_file_path}") # Optional: log success
    else:
         logger.error(f"EROARE CRITICĂ: Fișierul variabile.json nu a fost găsit la calea așteptată: {json_file_path}")
         taxa_timbru_keywords = {}
         taxa_timbru_nume_standard_json = {} # Fallback
except FileNotFoundError:
    logger.exception(f"EROARE CRITICĂ: Fișierul variabile.json nu a fost găsit. Calea căutată: {json_file_path}")
    taxa_timbru_keywords = {}
    taxa_timbru_nume_standard_json = {} # Fallback
except json.JSONDecodeError:
    logger.exception(f"EROARE CRITICĂ: Eroare la decodarea JSON din {json_file_path}. Verificați structura fișierului.")
    taxa_timbru_keywords = {}
    taxa_timbru_nume_standard_json = {} # Fallback
except Exception as e:
    logger.exception(f"EROARE CRITICĂ: O eroare neașteptată a apărut la încărcarea variabile.json: {e}")
    taxa_timbru_keywords = {}
    taxa_timbru_nume_standard_json = {} # Fallback


# Funcție helper pentru a obține keywords în siguranță
def get_keywords(key: str) -> List[str]:
    """Obține lista de keywords din dicționarul încărcat, cu fallback la listă goală."""
    default_list = []
    if not taxa_timbru_keywords:
         # logger.warning(f"Dicționarul 'taxa_timbru_keywords' este gol. Se returnează listă goală pentru cheia '{key}'.") # Poate fi prea verbos
         return default_list
    keywords_list = taxa_timbru_keywords.get(key)
    if keywords_list is None:
        # logger.warning(f"Cheia '{key}' nu a fost găsită în 'taxaTimbruKeywords' din variabile.json. Se returnează listă goală.") # Poate fi prea verbos
        return default_list
    if not isinstance(keywords_list, list):
        logger.warning(f"Valoarea pentru cheia '{key}' din 'taxaTimbruKeywords' nu este o listă. Se returnează listă goală.")
        return default_list
    return keywords_list

# Funcție helper nouă pentru a obține nume_standard din JSON cu fallback
def get_nume_standard_din_json(id_intern: str, default_value: str) -> str:
    """Obține 'nume_standard' din JSON dacă există, altfel folosește valoarea default (hardcodată)."""
    return taxa_timbru_nume_standard_json.get(id_intern, default_value)

# ============================================
# Constante pentru Actualizare Inflație (Art. 50)
# ============================================
DATA_ULTIMA_ACTUALIZARE_VALORI = "2025-03-31"

TAXA_MINIMA_ART3_1: float = 20.0
TAXA_20_LEI: float = 20.0
TAXA_50_LEI: float = 50.0
TAXA_100_LEI: float = 100.0
TAXA_200_LEI: float = 200.0
TAXA_300_LEI: float = 300.0
TAXA_1000_LEI: float = 1000.0
TAXA_COPIE_SIMPLA_PAG: float = 0.20
TAXA_LEGALIZARE_PAG_EX: float = 1.0
TAXA_CERTIFICAT_PAG: float = 1.0
TAXA_COPIE_HOT_DEF_EX: float = 5.0
TAXA_SUPRALEGALIZARE_MJ_INSCRIS: float = 10.0
TAXA_STABILIRE_CALITATE_PERS: float = 50.0

BAREM_ART31_PRAG1: float = 500.0
BAREM_ART31_PROC1: float = 0.08
BAREM_ART31_TAXA1_MIN: float = TAXA_MINIMA_ART3_1
BAREM_ART31_PRAG2: float = 5000.0
BAREM_ART31_TAXA_FIXA2: float = 40.0
BAREM_ART31_PROC2: float = 0.07
BAREM_ART31_PRAG3: float = 25000.0
BAREM_ART31_TAXA_FIXA3: float = 355.0
BAREM_ART31_PROC3: float = 0.05
BAREM_ART31_PRAG4: float = 50000.0
BAREM_ART31_TAXA_FIXA4: float = 1355.0
BAREM_ART31_PROC4: float = 0.03
BAREM_ART31_PRAG5: float = 250000.0
BAREM_ART31_TAXA_FIXA5: float = 2105.0
BAREM_ART31_PROC5: float = 0.02
BAREM_ART31_TAXA_FIXA6: float = 6105.0
BAREM_ART31_PROC6: float = 0.01

CONT_ADM_PATRIM_PROC: float = 0.10
CONT_ADM_PATRIM_PLAFON: float = TAXA_300_LEI

TAXA_VALOARE_REDUSA_PRAG: float = 2000.0
TAXA_VALOARE_REDUSA_S1: float = TAXA_50_LEI
TAXA_VALOARE_REDUSA_S2: float = TAXA_200_LEI
TAXA_REPUNERE_SITUATIE_PRAG: float = 5000.0
TAXA_REPUNERE_SITUATIE_S1: float = TAXA_50_LEI
TAXA_REPUNERE_SITUATIE_S2: float = TAXA_300_LEI
TAXA_ORD_PRESED_EVAL_PRAG: float = TAXA_VALOARE_REDUSA_PRAG
TAXA_ORD_PRESED_EVAL_S1: float = TAXA_VALOARE_REDUSA_S1
TAXA_ORD_PRESED_EVAL_S2: float = TAXA_VALOARE_REDUSA_S2
TAXA_ORD_PRESED_NEVAL: float = TAXA_20_LEI

# ============================================
# Baza de Date Centrală - TIPURI_CERERI
# ============================================
TIPURI_CERERI: Dict[str, Dict[str, Any]] = {
    "OUG80_ART3_1_GEN": {
        "id_intern": "OUG80_ART3_1_GEN",
        "nume_standard": get_nume_standard_din_json("OUG80_ART3_1_GEN", "Acțiune/Cerere evaluabilă în bani (Regulă Generală)"),
        "articol_referinta": "Art. 3(1)",
        "keywords": get_keywords("OUG80_ART3_1_GEN"),
        "regula_calcul_id": "CALC_ART3_1",
        "campuri_necesare": ["Valoare_Obiect"],
        "mod_determinare_valoare_implicit": "ART31_2_DECLARAT",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Patrimonial",
        "detalii_suplimentare": "Se aplică pentru orice cerere evaluabilă în bani pentru care nu există o regulă specială.",
        "intrebari_ghidare": ["Cerea dumneavoastră implică solicitarea unei sume de bani?", "Care este valoarea totală în lei solicitată?"],
    },
    "OUG80_ART3_2A_PRINC": {
        "id_intern": "OUG80_ART3_2A_PRINC",
        "nume_standard": get_nume_standard_din_json("OUG80_ART3_2A_PRINC", "Acțiune evaluabilă (principală)"),
        "articol_referinta": "Art. 3(1) / Art. 3(2)a",
        "keywords": get_keywords("OUG80_ART3_2A_PRINC"),
        "regula_calcul_id": "CALC_ART3_1",
        "campuri_necesare": ["Valoare_Obiect"],
        "mod_determinare_valoare_implicit": "ART31_2_DECLARAT",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Patrimonial",
        "detalii_suplimentare": "Atenție: Dobânzile, penalitățile, cheltuielile NU se taxează separat dacă sunt cerute în aceeași acțiune cu debitul principal (cf. Art. 3(2) lit. a)).",
        "intrebari_ghidare": ["Cerea dumneavoastră se referă la suma principală datorată?"],
    },
    "OUG80_ART3_2A_ACCESORIU_SCUTIT": {
        "id_intern": "OUG80_ART3_2A_ACCESORIU_SCUTIT",
        "nume_standard": get_nume_standard_din_json("OUG80_ART3_2A_ACCESORIU_SCUTIT", "Cerere dobânzi/penalități/cheltuieli (Accesoriu)"),
        "articol_referinta": "Art. 3(2) lit. a)",
        "keywords": get_keywords("OUG80_ART3_2A_ACCESORIU_SCUTIT"),
        "regula_calcul_id": "CALC_SCUTIT",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "NU",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": ["OUG80_ART3_1_GEN", "OUG80_ART3_2A_PRINC"],
        "necesita_actiune_subiacenta": False,
        "categorie": "Accesorii",
        "detalii_suplimentare": "Acest capăt de cerere este scutit dacă este formulat împreună cu cererea principală (debitul). Adăugați-l doar dacă doriți evidențierea separată în detalierea calculului.",
        "intrebari_ghidare": ["Acest capăt de cerere pentru dobânzi/penalități/cheltuieli este formulat împreună cu cererea principală (debitul)?"],
    },
    "OUG80_ART3_2B_SIMULATIE": {
        "id_intern": "OUG80_ART3_2B_SIMULATIE",
        "nume_standard": get_nume_standard_din_json("OUG80_ART3_2B_SIMULATIE", "Acțiune în simulație"),
        "articol_referinta": "Art. 3(2) lit. b)",
        "keywords": get_keywords("OUG80_ART3_2B_SIMULATIE"),
        "regula_calcul_id": "CALC_ART3_1",
        "campuri_necesare": ["Valoare_Obiect"],
        "mod_determinare_valoare_implicit": "ART31_VALOARE_ACT_PUBLIC",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Patrimonial",
        "detalii_suplimentare": "Se taxează conform Art. 3(1) la valoarea bunului/dreptului menționat în actul aparent/public.",
        "intrebari_ghidare": ["Acțiunea dvs. vizează constatarea simulației unui act?", "Care este valoarea bunului/dreptului menționat în actul public/aparent?"],
    },
    "OUG80_ART3_2C_CONST_DREPT_PATRIM": {
        "id_intern": "OUG80_ART3_2C_CONST_DREPT_PATRIM",
        "nume_standard": get_nume_standard_din_json("OUG80_ART3_2C_CONST_DREPT_PATRIM", "Acțiune constatare existență/inexistență drept patrimonial"),
        "articol_referinta": "Art. 3(2) lit. c)",
        "keywords": get_keywords("OUG80_ART3_2C_CONST_DREPT_PATRIM"),
        "regula_calcul_id": "CALC_ART3_1",
        "campuri_necesare": ["Valoare_Obiect"],
        "mod_determinare_valoare_implicit": "ART31_VALOARE_DREPT",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Patrimonial",
        "detalii_suplimentare": "Se taxează conform Art. 3(1) la valoarea dreptului contestat sau a cărui existență/inexistență se cere a fi constatată.",
        "intrebari_ghidare": ["Acțiunea dvs. vizează constatarea existenței sau inexistenței unui drept cu valoare economică?", "Care este valoarea estimată a acestui drept în lei?"],
    },
    "OUG80_ART3_2D_REVOCATORIE": {
        "id_intern": "OUG80_ART3_2D_REVOCATORIE",
        "nume_standard": get_nume_standard_din_json("OUG80_ART3_2D_REVOCATORIE", "Acțiune revocatorie (pauliană)"),
        "articol_referinta": "Art. 3(2) lit. d)",
        "keywords": get_keywords("OUG80_ART3_2D_REVOCATORIE"),
        "regula_calcul_id": "CALC_REVOCATORIE",
        "campuri_necesare": ["Valoare_Creanta_Creditor", "Valoare_Afectata_Prin_Act_Fraudulos"],
        "mod_determinare_valoare_implicit": "PREJUDICIU_REVOCATORIU",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Patrimonial",
        "detalii_suplimentare": "Se taxează conform Art. 3(1) la valoarea cea mai mică dintre valoarea creanței creditorului și valoarea bunurilor/drepturilor afectate prin actul fraudulos.",
        "intrebari_ghidare": ["Acțiunea dvs. vizează revocarea unui act făcut de debitor în frauda drepturilor dvs.?", "Care este valoarea creanței dvs. împotriva debitorului?", "Care este valoarea bunurilor/drepturilor afectate prin actul atacat?"],
    },
    "OUG80_ART3_2D_OBLICA": {
        "id_intern": "OUG80_ART3_2D_OBLICA",
        "nume_standard": get_nume_standard_din_json("OUG80_ART3_2D_OBLICA", "Acțiune oblică (subrogatorie)"),
        "articol_referinta": "Art. 3(2) lit. d)",
        "keywords": get_keywords("OUG80_ART3_2D_OBLICA"),
        "regula_calcul_id": "CALC_OBLICA",
        "campuri_necesare": ["Valoare_Creanta_Creditor", "Valoare_Obiect_Subiacent"],
        "mod_determinare_valoare_implicit": "PREJUDICIU_OBLIC",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": True,
        "categorie": "Patrimonial",
        "detalii_suplimentare": "Se taxează conform Art. 3(1) la valoarea cea mai mică dintre valoarea creanței creditorului și valoarea dreptului debitorului exercitat pe cale oblică.",
        "intrebari_ghidare": ["Acțiunea dvs. vizează exercitarea unui drept al debitorului dvs. în locul acestuia?", "Care este valoarea creanței dvs. împotriva debitorului?", "Care este valoarea dreptului debitorului pe care îl exercitați?"],
    },
    "OUG80_ART4_1_POSESORIE": {
        "id_intern": "OUG80_ART4_1_POSESORIE",
        "nume_standard": get_nume_standard_din_json("OUG80_ART4_1_POSESORIE", "Acțiune posesorie (litigiu privind posesia)"),
        "articol_referinta": "Art. 4(1)",
        "keywords": get_keywords("OUG80_ART4_1_POSESORIE"),
        "regula_calcul_id": "CALC_ART4_1",
        "campuri_necesare": ["Valoare_Bun_Imobil"],
        "mod_determinare_valoare_implicit": "ART31_3_IMPOZABIL",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Patrimonial",
        "detalii_suplimentare": "Taxa se calculează conform Art. 3(1) la 20% din valoarea bunului imobil la care se referă litigiul privind posesia.",
        "intrebari_ghidare": ["Litigiul dvs. se referă exclusiv la posesia unui bun imobil?", "Care este valoarea impozabilă/grilă notarială a bunului imobil în litigiu?"],
    },
    "OUG80_ART4_2_DEZMEMBRAMANT": {
        "id_intern": "OUG80_ART4_2_DEZMEMBRAMANT",
        "nume_standard": get_nume_standard_din_json("OUG80_ART4_2_DEZMEMBRAMANT", "Acțiune privind un dezmembrământ"),
        "articol_referinta": "Art. 4(2)",
        "keywords": get_keywords("OUG80_ART4_2_DEZMEMBRAMANT"),
        "regula_calcul_id": "CALC_ART4_2",
        "campuri_necesare": ["Valoare_Bun_Imobil"],
        "mod_determinare_valoare_implicit": "ART31_3_IMPOZABIL",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Patrimonial",
        "detalii_suplimentare": "Taxa se calculează conform Art. 3(1) la 20% din valoarea bunului imobil asupra căruia poartă dezmembrământul.",
        "intrebari_ghidare": ["Litigiul dvs. vizează constituirea/apărarea unui drept de uzufruct, uz, abitație sau superficie?", "Care este valoarea impozabilă/grilă notarială a bunului imobil afectat?"],
    },
    "OUG80_ART4_2_SERVITUTE": {
        "id_intern": "OUG80_ART4_2_SERVITUTE",
        "nume_standard": get_nume_standard_din_json("OUG80_ART4_2_SERVITUTE", "Acțiune privind o servitute"),
        "articol_referinta": "Art. 4(2)",
        "keywords": get_keywords("OUG80_ART4_2_SERVITUTE"),
        "regula_calcul_id": "CALC_ART4_2",
        "campuri_necesare": ["Valoare_Bun_Imobil"],
        "mod_determinare_valoare_implicit": "ART31_3_IMPOZABIL",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Patrimonial",
        "detalii_suplimentare": "Taxa se calculează conform Art. 3(1) la 20% din valoarea bunului imobil relevant (fond dominant sau aservit).",
        "intrebari_ghidare": ["Litigiul dvs. vizează constituirea/apărarea unei servituți?", "Care este valoarea impozabilă/grilă notarială a fondului relevant?"],
    },
    "OUG80_ART5_1_PARTAJ_JUDICIAR": {
        "id_intern": "OUG80_ART5_1_PARTAJ_JUDICIAR",
        "nume_standard": get_nume_standard_din_json("OUG80_ART5_1_PARTAJ_JUDICIAR", "Cerere de partaj judiciar (Componentă)"),
        "articol_referinta": "Art. 5(1)",
        "keywords": get_keywords("OUG80_ART5_1_PARTAJ_JUDICIAR"),
        "regula_calcul_id": "CALC_ART5_1_COMP",
        "campuri_necesare": ["Valoare_Obiect"],
        "mod_determinare_valoare_implicit": "ART31_3_IMPOZABIL",
        "taxare_separata_implicit": "NU",
        "grup_exceptie_insumare": "PARTAJ_ART5",
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Patrimonial",
        "detalii_suplimentare": "Se adaugă un capăt de cerere pentru fiecare masă partajabilă. Taxa finală va fi 50% din taxa calculată conform Art. 3(1) la valoarea cea mai mare dintre mase (Art. 5(2)).",
        "intrebari_ghidare": ["Cerea dvs. vizează împărțirea unor bunuri aflate în coproprietate/indiviziune?", "Care este valoarea totală a bunurilor din această masă partajabilă?"],
    },
    "OUG80_ART5_3_STAB_CALIT": {
        "id_intern": "OUG80_ART5_3_STAB_CALIT",
        "nume_standard": get_nume_standard_din_json("OUG80_ART5_3_STAB_CALIT", "Cerere stabilire calitate coproprietar/moștenitor"),
        "articol_referinta": "Art. 5(3)",
        "keywords": get_keywords("OUG80_ART5_3_STAB_CALIT"),
        "regula_calcul_id": "CALC_ART5_3",
        "campuri_necesare": ["Numar_Coproprietari_Mostenitori"],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Accesorii",
        "detalii_suplimentare": f"Se taxează separat cu {TAXA_STABILIRE_CALITATE_PERS:,.2f} lei pentru fiecare persoană a cărei calitate se cere a fi stabilită.",
        "intrebari_ghidare": ["Cererea dvs. include și stabilirea calității de coproprietar/moștenitor pentru una sau mai multe persoane?", "Pentru câte persoane se solicită stabilirea calității?"],
    },
    "OUG80_ART6_1_VAL_REDUSA": {
        "id_intern": "OUG80_ART6_1_VAL_REDUSA",
        "nume_standard": get_nume_standard_din_json("OUG80_ART6_1_VAL_REDUSA", "Cerere cu valoare redusă (Titlul X CPC)"),
        "articol_referinta": "Art. 6(1)",
        "keywords": get_keywords("OUG80_ART6_1_VAL_REDUSA"),
        "regula_calcul_id": "CALC_ART6_1",
        "campuri_necesare": ["Valoare_Obiect"],
        "mod_determinare_valoare_implicit": "ART31_2_DECLARAT",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Proceduri Speciale",
        "detalii_suplimentare": f"Taxă {TAXA_VALOARE_REDUSA_S1:,.2f} lei (<= {TAXA_VALOARE_REDUSA_PRAG:,.0f} lei) / {TAXA_VALOARE_REDUSA_S2:,.2f} lei (> {TAXA_VALOARE_REDUSA_PRAG:,.0f} lei).",
        "intrebari_ghidare": ["Formulați o cerere conform procedurii cu privire la cererile de valoare redusă?", "Care este valoarea creanței?"],
    },
    "OUG80_ART6_2_ORD_PLATA": {
        "id_intern": "OUG80_ART6_2_ORD_PLATA",
        "nume_standard": get_nume_standard_din_json("OUG80_ART6_2_ORD_PLATA", "Ordonanță de plată (Titlul IX CPC)"),
        "articol_referinta": "Art. 6(2)",
        "keywords": get_keywords("OUG80_ART6_2_ORD_PLATA"),
        "regula_calcul_id": "CALC_ART6_2",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Proceduri Speciale",
        "detalii_suplimentare": f"Taxă fixă {TAXA_200_LEI:,.2f} lei.",
        "intrebari_ghidare": ["Formulați o cerere de ordonanță de plată?"],
    },
    "OUG80_ART6_2_SOMATIE_UE": {
        "id_intern": "OUG80_ART6_2_SOMATIE_UE",
        "nume_standard": get_nume_standard_din_json("OUG80_ART6_2_SOMATIE_UE", "Cerere privind Somația Europeană de plată"),
        "articol_referinta": "Art. 6(2)",
        "keywords": get_keywords("OUG80_ART6_2_SOMATIE_UE"),
        "regula_calcul_id": "CALC_ART6_2",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Proceduri Speciale",
        "detalii_suplimentare": f"Taxă fixă {TAXA_200_LEI:,.2f} lei.",
        "intrebari_ghidare": ["Formulați o cerere de somație europeană de plată?"],
    },
    "OUG80_ART6_2_1_OPOZ_SOMATIE": {
        "id_intern": "OUG80_ART6_2_1_OPOZ_SOMATIE",
        "nume_standard": get_nume_standard_din_json("OUG80_ART6_2_1_OPOZ_SOMATIE", "Opoziție împotriva Somației Europene de plată"),
        "articol_referinta": "Art. 6(2^1)",
        "keywords": get_keywords("OUG80_ART6_2_1_OPOZ_SOMATIE"),
        "regula_calcul_id": "CALC_ART6_2_1",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Proceduri Speciale",
        "detalii_suplimentare": f"Taxă fixă {TAXA_100_LEI:,.2f} lei.",
        "intrebari_ghidare": ["Formulați o opoziție la o somație europeană de plată?"],
    },
    "OUG80_ART6_2_1_REEX_VAL_RED": {
        "id_intern": "OUG80_ART6_2_1_REEX_VAL_RED",
        "nume_standard": get_nume_standard_din_json("OUG80_ART6_2_1_REEX_VAL_RED", "Cerere reexaminare hotărâre valoare redusă"),
        "articol_referinta": "Art. 6(2^1)",
        "keywords": get_keywords("OUG80_ART6_2_1_REEX_VAL_RED"),
        "regula_calcul_id": "CALC_ART6_2_1",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Căi de Atac",
        "detalii_suplimentare": f"Taxă fixă {TAXA_100_LEI:,.2f} lei.",
        "intrebari_ghidare": ["Formulați o cerere de reexaminare a hotărârii date într-o cerere cu valoare redusă?"],
    },
    "OUG80_ART6_3_EVACUARE": {
        "id_intern": "OUG80_ART6_3_EVACUARE",
        "nume_standard": get_nume_standard_din_json("OUG80_ART6_3_EVACUARE", "Cerere de evacuare (Titlul XI CPC)"),
        "articol_referinta": "Art. 6(3)",
        "keywords": get_keywords("OUG80_ART6_3_EVACUARE"),
        "regula_calcul_id": "CALC_ART6_3",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Proceduri Speciale",
        "detalii_suplimentare": f"Taxă fixă {TAXA_100_LEI:,.2f} lei pentru procedura specială de evacuare.",
        "intrebari_ghidare": ["Formulați o cerere de evacuare conform procedurii speciale din Titlul XI CPC?"],
    },
    "OUG80_ART6_4_ORD_PRESED": {
        "id_intern": "OUG80_ART6_4_ORD_PRESED",
        "nume_standard": get_nume_standard_din_json("OUG80_ART6_4_ORD_PRESED", "Cerere de ordonanță președințială"),
        "articol_referinta": "Art. 6(4)",
        "keywords": get_keywords("OUG80_ART6_4_ORD_PRESED"),
        "regula_calcul_id": "CALC_ART6_4",
        "campuri_necesare": ["Este_Evaluabil", "Valoare_Obiect"],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Proceduri Speciale",
        "detalii_suplimentare": f"Neevaluabilă: {TAXA_ORD_PRESED_NEVAL:,.2f} lei. Evaluabilă: {TAXA_ORD_PRESED_EVAL_S1:,.2f} lei (<= {TAXA_ORD_PRESED_EVAL_PRAG:,.0f} lei) / {TAXA_ORD_PRESED_EVAL_S2:,.2f} lei (> {TAXA_ORD_PRESED_EVAL_PRAG:,.0f} lei).",
        "intrebari_ghidare": ["Formulați o cerere de ordonanță președințială?", "Cererea are caracter patrimonial (evaluabilă în bani)?", "Dacă da, care este valoarea estimată?"],
    },
    "OUG80_ART7_1_DAUNE_MORALE": {
        "id_intern": "OUG80_ART7_1_DAUNE_MORALE",
        "nume_standard": get_nume_standard_din_json("OUG80_ART7_1_DAUNE_MORALE", "Acțiune reparare prejudiciu moral (onoare, etc.)"),
        "articol_referinta": "Art. 7(1)",
        "keywords": get_keywords("OUG80_ART7_1_DAUNE_MORALE"),
        "regula_calcul_id": "CALC_ART7_1",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Nepatrimonial",
        "detalii_suplimentare": f"Taxă fixă {TAXA_100_LEI:,.2f} lei, indiferent de cuantumul despăgubirilor solicitate.",
        "intrebari_ghidare": ["Solicitați despăgubiri pentru atingerea adusă onoarei, demnității sau reputației?"],
    },
    "OUG80_ART7_2_VATAMARI": {
        "id_intern": "OUG80_ART7_2_VATAMARI",
        "nume_standard": get_nume_standard_din_json("OUG80_ART7_2_VATAMARI", "Acțiune despăgubiri vătămări fizice/psihice"),
        "articol_referinta": "Art. 7(2)",
        "keywords": get_keywords("OUG80_ART7_2_VATAMARI"),
        "regula_calcul_id": "CALC_ART7_2",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Nepatrimonial",
        "detalii_suplimentare": f"Taxă fixă {TAXA_100_LEI:,.2f} lei. Nu include cererile privind dreptul la muncă sau asigurări sociale (Art. 29).",
        "intrebari_ghidare": ["Solicitați despăgubiri pentru vătămarea integrității fizice, psihice sau a sănătății?", "Cererea NU se referă la accidente de muncă sau boli profesionale?"],
    },
    "OUG80_ART8_1A_CONST_NEPATRIM": {
        "id_intern": "OUG80_ART8_1A_CONST_NEPATRIM",
        "nume_standard": get_nume_standard_din_json("OUG80_ART8_1A_CONST_NEPATRIM", "Acțiune constatare/nulitate/anulare act NEPATRIMONIAL"),
        "articol_referinta": "Art. 8(1) lit. a)",
        "keywords": get_keywords("OUG80_ART8_1A_CONST_NEPATRIM"),
        "regula_calcul_id": "CALC_ART8_1_ABC",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Nepatrimonial",
        "detalii_suplimentare": f"Taxă fixă {TAXA_100_LEI:,.2f} lei. Doar pentru acte nepatrimoniale.",
        "intrebari_ghidare": ["Cerea dvs. vizează constatarea/nulitatea/anularea unui act juridic fără valoare economică directă?"],
    },
    "OUG80_ART8_1B_FOLOSINTA_BUN": {
        "id_intern": "OUG80_ART8_1B_FOLOSINTA_BUN",
        "nume_standard": get_nume_standard_din_json("OUG80_ART8_1B_FOLOSINTA_BUN", "Acțiune folosință bun închiriat/arendat (fără pretenții)"),
        "articol_referinta": "Art. 8(1) lit. b)",
        "keywords": get_keywords("OUG80_ART8_1B_FOLOSINTA_BUN"),
        "regula_calcul_id": "CALC_ART8_1_ABC",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Nepatrimonial",
        "detalii_suplimentare": f"Taxă fixă {TAXA_100_LEI:,.2f} lei. Doar dacă nu se solicită și sume de bani.",
        "intrebari_ghidare": ["Cerea dvs. vizează exclusiv dreptul de folosință a unui bun închiriat/arendat, fără a cere și plata unor sume?"],
    },
    "OUG80_ART8_1C_INTERES_VIITOR": {
        "id_intern": "OUG80_ART8_1C_INTERES_VIITOR",
        "nume_standard": get_nume_standard_din_json("OUG80_ART8_1C_INTERES_VIITOR", "Acțiune apărare drept nepatrimonial viitor"),
        "articol_referinta": "Art. 8(1) lit. c)",
        "keywords": get_keywords("OUG80_ART8_1C_INTERES_VIITOR"),
        "regula_calcul_id": "CALC_ART8_1_ABC",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Nepatrimonial",
        "detalii_suplimentare": f"Taxă fixă {TAXA_100_LEI:,.2f} lei.",
        "intrebari_ghidare": ["Cerea dvs. vizează apărarea unui drept nepatrimonial care nu s-a încălcat încă, dar există un interes actual?"],
    },
    "OUG80_ART8_1D_GRANITUIRE": {
        "id_intern": "OUG80_ART8_1D_GRANITUIRE",
        "nume_standard": get_nume_standard_din_json("OUG80_ART8_1D_GRANITUIRE", "Acțiune în grănițuire"),
        "articol_referinta": "Art. 8(1) lit. d)",
        "keywords": get_keywords("OUG80_ART8_1D_GRANITUIRE"),
        "regula_calcul_id": "CALC_ART8_1_D",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Nepatrimonial",
        "detalii_suplimentare": f"Taxă fixă {TAXA_100_LEI:,.2f} lei. Dacă se cere și revendicarea unei porțiuni de teren (OUG80_REVEND_IMOBIL_PT_DESF), aceasta din urmă se taxează separat, iar cererea de grănițuire este scutită (verificat în logica principală).",
        "intrebari_ghidare": ["Cerea dvs. vizează stabilirea liniei de hotar între proprietăți?", "Solicitați și restituirea unei suprafețe de teren (revendicare)?"],
    },
    "OUG80_REVEND_IMOBIL_PT_DESF": {
        "id_intern": "OUG80_REVEND_IMOBIL_PT_DESF",
        "nume_standard": get_nume_standard_din_json("OUG80_REVEND_IMOBIL_PT_DESF", "Revendicare Imobil (cu Grănițuire)"),
        "articol_referinta": "Art. 3(1) rap. la Art. 8(1)d",
        "keywords": get_keywords("OUG80_REVEND_IMOBIL_PT_DESF"),
        "regula_calcul_id": "CALC_REVEND_IMOBIL",
        "campuri_necesare": ["Valoare_Bun_Imobil"],
        "mod_determinare_valoare_implicit": "ART31_3_IMPOZABIL",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Patrimonial",
        "detalii_suplimentare": "Se taxează conform Art. 3(1) la valoarea impozabilă/grilă a terenului revendicat. Cererea de grănițuire asociată este scutită.",
        "intrebari_ghidare": ["Solicitați atât stabilirea hotarului cât și restituirea unei suprafețe de teren?", "Care este valoarea impozabilă a terenului revendicat?"],
    },
    "OUG80_ART8_2_REPUNERE_NEACCES": {
        "id_intern": "OUG80_ART8_2_REPUNERE_NEACCES",
        "nume_standard": get_nume_standard_din_json("OUG80_ART8_2_REPUNERE_NEACCES", "Cerere repunere în situația anterioară (NEACCESORIE)"),
        "articol_referinta": "Art. 8(2)",
        "keywords": get_keywords("OUG80_ART8_2_REPUNERE_NEACCES"),
        "regula_calcul_id": "CALC_ART8_2",
        "campuri_necesare": ["Valoare_Obiect"],
        "mod_determinare_valoare_implicit": "ART31_COSTURI_REPUNERE",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Patrimonial",
        "detalii_suplimentare": f"Taxă {TAXA_REPUNERE_SITUATIE_S1:,.2f} lei (<= {TAXA_REPUNERE_SITUATIE_PRAG:,.0f} lei) / {TAXA_REPUNERE_SITUATIE_S2:,.2f} lei (> {TAXA_REPUNERE_SITUATIE_PRAG:,.0f} lei). Se aplică doar dacă NU e accesorie (caz în care ar fi scutită).",
        "intrebari_ghidare": ["Solicitați repunerea în situația anterioară ca o cerere distinctă (nu ca accesoriu)?", "Care este valoarea estimată a lucrărilor/prejudiciului pentru repunere?"],
    },
    "OUG80_ART9_A_RECUZARE": {
        "id_intern": "OUG80_ART9_A_RECUZARE",
        "nume_standard": get_nume_standard_din_json("OUG80_ART9_A_RECUZARE", "Cerere de recuzare"),
        "articol_referinta": "Art. 9 lit. a)",
        "keywords": get_keywords("OUG80_ART9_A_RECUZARE"),
        "regula_calcul_id": "CALC_ART9_A",
        "campuri_necesare": ["Numar_Participanti_Recuzati"],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Incidentale",
        "detalii_suplimentare": f"Taxă {TAXA_100_LEI:,.2f} lei pentru fiecare persoană a cărei recuzare se solicită.",
        "intrebari_ghidare": ["Formulați o cerere de recuzare?", "Pentru câte persoane solicitați recuzarea?"],
    },
    "OUG80_ART9_B_STRAMUTARE": {
        "id_intern": "OUG80_ART9_B_STRAMUTARE",
        "nume_standard": get_nume_standard_din_json("OUG80_ART9_B_STRAMUTARE", "Cerere de strămutare"),
        "articol_referinta": "Art. 9 lit. b)",
        "keywords": get_keywords("OUG80_ART9_B_STRAMUTARE"),
        "regula_calcul_id": "CALC_ART9_B",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Incidentale",
        "detalii_suplimentare": f"Taxă fixă {TAXA_100_LEI:,.2f} lei.",
        "intrebari_ghidare": ["Formulați o cerere de strămutare a judecării cauzei?"],
    },
    "OUG80_ART9_C_REPUNERE_TERMEN": {
        "id_intern": "OUG80_ART9_C_REPUNERE_TERMEN",
        "nume_standard": get_nume_standard_din_json("OUG80_ART9_C_REPUNERE_TERMEN", "Cerere de repunere în termen"),
        "articol_referinta": "Art. 9 lit. c)",
        "keywords": get_keywords("OUG80_ART9_C_REPUNERE_TERMEN"),
        "regula_calcul_id": "CALC_ART9_CDEF",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Incidentale",
        "detalii_suplimentare": f"Taxă fixă {TAXA_20_LEI:,.2f} lei.",
        "intrebari_ghidare": ["Formulați o cerere de repunere în termenul legal?"],
    },
    "OUG80_ART9_D_CONST_PERIMARE": {
        "id_intern": "OUG80_ART9_D_CONST_PERIMARE",
        "nume_standard": get_nume_standard_din_json("OUG80_ART9_D_CONST_PERIMARE", "Cerere de constatare a perimării"),
        "articol_referinta": "Art. 9 lit. d)",
        "keywords": get_keywords("OUG80_ART9_D_CONST_PERIMARE"),
        "regula_calcul_id": "CALC_ART9_CDEF",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Incidentale",
        "detalii_suplimentare": f"Taxă fixă {TAXA_20_LEI:,.2f} lei.",
        "intrebari_ghidare": ["Formulați o cerere pentru constatarea perimării judecății?"],
    },
    "OUG80_ART9_E_REEX_TAXA": {
        "id_intern": "OUG80_ART9_E_REEX_TAXA",
        "nume_standard": get_nume_standard_din_json("OUG80_ART9_E_REEX_TAXA", "Cerere reexaminare încheiere stabilire taxă timbru"),
        "articol_referinta": "Art. 9 lit. e)",
        "keywords": get_keywords("OUG80_ART9_E_REEX_TAXA"),
        "regula_calcul_id": "CALC_ART9_CDEF",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Incidentale",
        "detalii_suplimentare": f"Taxă fixă {TAXA_20_LEI:,.2f} lei.",
        "intrebari_ghidare": ["Formulați o cerere de reexaminare a încheierii prin care s-a stabilit taxa de timbru?"],
    },
    "OUG80_ART9_F_REEX_AMENDA_ANULARE": {
        "id_intern": "OUG80_ART9_F_REEX_AMENDA_ANULARE",
        "nume_standard": get_nume_standard_din_json("OUG80_ART9_F_REEX_AMENDA_ANULARE", "Cerere reexaminare amendă/despăgubire/anulare cerere"),
        "articol_referinta": "Art. 9 lit. f)",
        "keywords": get_keywords("OUG80_ART9_F_REEX_AMENDA_ANULARE"),
        "regula_calcul_id": "CALC_ART9_CDEF",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Incidentale",
        "detalii_suplimentare": f"Taxă fixă {TAXA_20_LEI:,.2f} lei pentru cererea de reexaminare împotriva încheierii de anulare a cererii sau de aplicare a amenzii/despăgubirii.",
        "intrebari_ghidare": ["Formulați o cerere de reexaminare a încheierii prin care s-a anulat cererea sau s-a aplicat o amendă/despăgubire judiciară?"],
    },
    "OUG80_ART9_G_REPUNERE_ROL": {
        "id_intern": "OUG80_ART9_G_REPUNERE_ROL",
        "nume_standard": get_nume_standard_din_json("OUG80_ART9_G_REPUNERE_ROL", "Cerere de repunere pe rol (culpa părții)"),
        "articol_referinta": "Art. 9 lit. g)",
        "keywords": get_keywords("OUG80_ART9_G_REPUNERE_ROL"),
        "regula_calcul_id": "CALC_ART9_G",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Incidentale",
        "detalii_suplimentare": "Taxa este 50% din taxa de timbru datorată pentru cererea a cărei judecată a fost suspendată.",
        "intrebari_ghidare": ["Solicitați repunerea pe rol a unei cauze suspendate din vina dvs.?", "Introduceți taxa achitată inițial pentru cererea principală în secțiunea 'Date Generale'."]
    },
    "OUG80_ART9_H_REFACERE_INSCRIS": {
        "id_intern": "OUG80_ART9_H_REFACERE_INSCRIS",
        "nume_standard": get_nume_standard_din_json("OUG80_ART9_H_REFACERE_INSCRIS", "Cerere refacere înscrisuri/hotărâri dispărute"),
        "articol_referinta": "Art. 9 lit. h)",
        "keywords": get_keywords("OUG80_ART9_H_REFACERE_INSCRIS"),
        "regula_calcul_id": "CALC_ART9_H",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Incidentale",
        "detalii_suplimentare": f"Taxă fixă {TAXA_50_LEI:,.2f} lei.",
        "intrebari_ghidare": ["Solicitați refacerea unor înscrisuri sau hotărâri judecătorești dispărute?"],
    },
    "OUG80_ART9_I_COPIE_SIMPLA": {
        "id_intern": "OUG80_ART9_I_COPIE_SIMPLA",
        "nume_standard": get_nume_standard_din_json("OUG80_ART9_I_COPIE_SIMPLA", "Cerere eliberare copii simple"),
        "articol_referinta": "Art. 9 lit. i)",
        "keywords": get_keywords("OUG80_ART9_I_COPIE_SIMPLA"),
        "regula_calcul_id": "CALC_ART9_I",
        "campuri_necesare": ["Numar_Pagini"],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Cereri Diverse",
        "detalii_suplimentare": f"Taxă {TAXA_COPIE_SIMPLA_PAG:.2f} lei pe pagină.",
        "intrebari_ghidare": ["Solicitați copii simple după înscrisuri din dosar?", "Câte pagini estimați?"],
    },
    "OUG80_ART9_J_LEGALIZARE_COPIE": {
        "id_intern": "OUG80_ART9_J_LEGALIZARE_COPIE",
        "nume_standard": get_nume_standard_din_json("OUG80_ART9_J_LEGALIZARE_COPIE", "Cerere legalizare copie"),
        "articol_referinta": "Art. 9 lit. j)",
        "keywords": get_keywords("OUG80_ART9_J_LEGALIZARE_COPIE"),
        "regula_calcul_id": "CALC_ART9_J",
        "campuri_necesare": ["Numar_Pagini", "Numar_Exemplare"],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Cereri Diverse",
        "detalii_suplimentare": f"Taxă {TAXA_LEGALIZARE_PAG_EX:,.2f} leu pe pagină, pentru fiecare exemplar legalizat.",
        "intrebari_ghidare": ["Solicitați legalizarea unor copii după înscrisuri aflate la dosar?", "Câte pagini are înscrisul original?", "Câte exemplare legalizate doriți?"],
    },
    "OUG80_ART9_K_CERTIFICAT": {
        "id_intern": "OUG80_ART9_K_CERTIFICAT",
        "nume_standard": get_nume_standard_din_json("OUG80_ART9_K_CERTIFICAT", "Cerere eliberare certificat (grefă, fapte)"),
        "articol_referinta": "Art. 9 lit. k)",
        "keywords": get_keywords("OUG80_ART9_K_CERTIFICAT"),
        "regula_calcul_id": "CALC_ART9_K",
        "campuri_necesare": ["Numar_Pagini"],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Cereri Diverse",
        "detalii_suplimentare": f"Taxă {TAXA_CERTIFICAT_PAG:,.2f} leu pe pagină.",
        "intrebari_ghidare": ["Solicitați eliberarea unui certificat de grefă sau care atestă fapte/situații din dosar?", "Câte pagini estimați că va avea certificatul?"],
    },
    "OUG80_ART9_L_COPIE_HOT_DEF": {
        "id_intern": "OUG80_ART9_L_COPIE_HOT_DEF",
        "nume_standard": get_nume_standard_din_json("OUG80_ART9_L_COPIE_HOT_DEF", "Cerere copie hotărâre (definitivă)"),
        "articol_referinta": "Art. 9 lit. l)",
        "keywords": get_keywords("OUG80_ART9_L_COPIE_HOT_DEF"),
        "regula_calcul_id": "CALC_ART9_L",
        "campuri_necesare": ["Numar_Exemplare"],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Cereri Diverse",
        "detalii_suplimentare": f"Taxă {TAXA_COPIE_HOT_DEF_EX:,.2f} lei pentru fiecare exemplar de hotărâre cu mențiunea că este definitivă.",
        "intrebari_ghidare": ["Solicitați eliberarea unei copii a hotărârii cu mențiunea că este definitivă?", "Câte exemplare doriți?"],
    },
    "OUG80_ART10_1A_INCUV_EXEC": {
        "id_intern": "OUG80_ART10_1A_INCUV_EXEC",
        "nume_standard": get_nume_standard_din_json("OUG80_ART10_1A_INCUV_EXEC", "Cerere încuviințare executare silită"),
        "articol_referinta": "Art. 10(1) lit. a)",
        "keywords": get_keywords("OUG80_ART10_1A_INCUV_EXEC"),
        "regula_calcul_id": "CALC_ART10_1A",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Executare",
        "detalii_suplimentare": f"Taxă fixă {TAXA_20_LEI:,.2f} lei per cerere.",
        "intrebari_ghidare": ["Formulați o cerere de încuviințare a executării silite?"],
    },
    "OUG80_ART10_1B_SUSP_EXEC": {
        "id_intern": "OUG80_ART10_1B_SUSP_EXEC",
        "nume_standard": get_nume_standard_din_json("OUG80_ART10_1B_SUSP_EXEC", "Cerere suspendare executare silită"),
        "articol_referinta": "Art. 10(1) lit. b)",
        "keywords": get_keywords("OUG80_ART10_1B_SUSP_EXEC"),
        "regula_calcul_id": "CALC_ART10_1B",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Executare",
        "detalii_suplimentare": f"Taxă fixă {TAXA_50_LEI:,.2f} lei.",
        "intrebari_ghidare": ["Solicitați suspendarea (eventual provizorie) a executării silite?"],
    },
    "OUG80_ART10_2_3_CONTEST_EXEC": {
        "id_intern": "OUG80_ART10_2_3_CONTEST_EXEC",
        "nume_standard": get_nume_standard_din_json("OUG80_ART10_2_3_CONTEST_EXEC", "Contestație la executare"),
        "articol_referinta": "Art. 10(2) și (3)",
        "keywords": get_keywords("OUG80_ART10_2_3_CONTEST_EXEC"),
        "regula_calcul_id": "CALC_ART10_2_3",
        "campuri_necesare": [
            "Este_Evaluabil", "Este_Contestatie_Executare_Pe_Fond",
            "Valoare_Obiect", "Valoare_Bunuri_Contestate_Executare", "Valoare_Debit_Urmarit_Executare"
        ],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Executare",
        "detalii_suplimentare": f"Neevaluabilă (Art. 10(2) teza III): {TAXA_100_LEI:,.2f} lei.\nEvaluabilă (acte/refuz executor - Art. 10(2) teza I/II): Taxa Art.3(1) la min(val bunuri, val debit dacă debit<bunuri) plafonată la {TAXA_1000_LEI:,.0f} lei.\nContestație pe fond (Art. 10(3)): Taxa Art.3(1) la valoarea obiectului.",
        "intrebari_ghidare": ["Formulați o contestație la executare?", "Vizează și fondul dreptului?", "Dacă nu vizează fondul, este evaluabilă (vizează acte/refuz executor)?", "Dacă vizează fondul, care este valoarea?", "Dacă este evaluabilă (dar nu pe fond), care e valoarea bunurilor contestate și a debitului urmărit?"],
    },
    "OUG80_ART10_4_INTOARC_EXEC": {
        "id_intern": "OUG80_ART10_4_INTOARC_EXEC",
        "nume_standard": get_nume_standard_din_json("OUG80_ART10_4_INTOARC_EXEC", "Cerere întoarcere executare silită"),
        "articol_referinta": "Art. 10(4)",
        "keywords": get_keywords("OUG80_ART10_4_INTOARC_EXEC"),
        "regula_calcul_id": "CALC_ART10_4",
        "campuri_necesare": ["Valoare_Obiect"],
        "mod_determinare_valoare_implicit": "ART31_VALOARE_RESTITUIRE",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Executare",
        "detalii_suplimentare": f"Taxă {TAXA_REPUNERE_SITUATIE_S1:,.2f} lei (<= {TAXA_REPUNERE_SITUATIE_PRAG:,.0f} lei) / {TAXA_REPUNERE_SITUATIE_S2:,.2f} lei (> {TAXA_REPUNERE_SITUATIE_PRAG:,.0f} lei) la valoarea restituirii.",
        "intrebari_ghidare": ["Solicitați întoarcerea executării silite?", "Care este valoarea bunurilor/sumelor a căror restituire o cereți?"],
    },
    "OUG80_ART11_A_CONSFINȚIRE": {
        "id_intern": "OUG80_ART11_A_CONSFINȚIRE",
        "nume_standard": get_nume_standard_din_json("OUG80_ART11_A_CONSFINȚIRE", "Cerere consfințire înțelegere/acord mediere"),
        "articol_referinta": "Art. 11 lit. a)",
        "keywords": get_keywords("OUG80_ART11_A_CONSFINȚIRE"),
        "regula_calcul_id": "CALC_ART11_A",
        "campuri_necesare": [
            "Contine_Transfer_Imobiliar", "Valoare_Bun_Imobil",
            "Contine_Partaj", "Valoare_Obiect"
        ],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Proceduri Speciale",
        "detalii_suplimentare": f"Taxă bază {TAXA_20_LEI:,.2f} lei + 50% taxa partaj (dacă e cazul, calculată la 'Valoare_Obiect') + 50% taxa revendicare imobiliară (dacă e cazul, calculată la 'Valoare_Bun_Imobil').",
        "intrebari_ghidare": ["Solicitați consfințirea unei înțelegeri/acord de mediere?", "Include transfer imobiliar?", "Dacă da, valoarea celui mai mare imobil?", "Include partaj?", "Dacă da, valoarea masei partajabile?"],
    },
    "OUG80_ART11_B_MASURI_ASIG": {
        "id_intern": "OUG80_ART11_B_MASURI_ASIG",
        "nume_standard": get_nume_standard_din_json("OUG80_ART11_B_MASURI_ASIG", "Cerere măsuri asigurătorii"),
        "articol_referinta": "Art. 11 lit. b)",
        "keywords": get_keywords("OUG80_ART11_B_MASURI_ASIG"),
        "regula_calcul_id": "CALC_ART11_B",
        "campuri_necesare": ["Este_Nava_Aeronava", "Este_Ordonanta_UE_Indisponibilizare"],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Incidentale",
        "detalii_suplimentare": f"Taxă {TAXA_100_LEI:,.2f} lei (general); {TAXA_1000_LEI:,.2f} lei (nave/aeronave); {TAXA_100_LEI:,.2f} lei (Ord. UE conturi).",
        "intrebari_ghidare": ["Solicitați o măsură asigurătorie?", "Vizează navă/aeronavă?", "Este Ord. UE indisponibilizare conturi?"],
    },
    "OUG80_ART11_C_CONTEST_TERGIV": {
        "id_intern": "OUG80_ART11_C_CONTEST_TERGIV",
        "nume_standard": get_nume_standard_din_json("OUG80_ART11_C_CONTEST_TERGIV", "Contestație tergiversare proces / Plângere"),
        "articol_referinta": "Art. 11 lit. c)",
        "keywords": get_keywords("OUG80_ART11_C_CONTEST_TERGIV"),
        "regula_calcul_id": "CALC_ART11_C",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Incidentale",
        "detalii_suplimentare": f"Taxă fixă {TAXA_20_LEI:,.2f} lei.",
        "intrebari_ghidare": ["Formulați o contestație privind tergiversarea procesului sau o plângere împotriva actelor procurorului?"],
    },
    "OUG80_ART12_A_PARTID": {
        "id_intern": "OUG80_ART12_A_PARTID",
        "nume_standard": get_nume_standard_din_json("OUG80_ART12_A_PARTID", "Înregistrare/Modificare Partid Politic/Alianță"),
        "articol_referinta": "Art. 12 lit. a)",
        "keywords": get_keywords("OUG80_ART12_A_PARTID"),
        "regula_calcul_id": "CALC_ART12_A",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Persoane Juridice",
        "detalii_suplimentare": f"Taxă fixă {TAXA_300_LEI:,.2f} lei.",
        "intrebari_ghidare": ["Cererea vizează înregistrarea sau modificarea actelor constitutive ale unui partid/alianțe politice?"],
    },
    "OUG80_ART12_B_SINDICAT_PATRONAT": {
        "id_intern": "OUG80_ART12_B_SINDICAT_PATRONAT",
        "nume_standard": get_nume_standard_din_json("OUG80_ART12_B_SINDICAT_PATRONAT", "Dobândire PJ/Modificare Sindicate/Patronate/Uniuni"),
        "articol_referinta": "Art. 12 lit. b)",
        "keywords": get_keywords("OUG80_ART12_B_SINDICAT_PATRONAT"),
        "regula_calcul_id": "CALC_ART12_B",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Persoane Juridice",
        "detalii_suplimentare": f"Taxă fixă {TAXA_200_LEI:,.2f} lei.",
        "intrebari_ghidare": ["Cererea vizează dobândirea personalității juridice sau modificarea actelor unui sindicat/patronat/uniuni etc.?"],
    },
    "OUG80_ART12_C_ASOC_FUNDATIE": {
        "id_intern": "OUG80_ART12_C_ASOC_FUNDATIE",
        "nume_standard": get_nume_standard_din_json("OUG80_ART12_C_ASOC_FUNDATIE", "Dobândire PJ/Modificare Asociații/Fundații"),
        "articol_referinta": "Art. 12 lit. c)",
        "keywords": get_keywords("OUG80_ART12_C_ASOC_FUNDATIE"),
        "regula_calcul_id": "CALC_ART12_C",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Persoane Juridice",
        "detalii_suplimentare": f"Taxă fixă {TAXA_100_LEI:,.2f} lei.",
        "intrebari_ghidare": ["Cererea vizează dobândirea personalității juridice sau modificarea actelor unei asociații/fundații?"],
    },
    "OUG80_ART13_A_DREPT_AUTOR": {
        "id_intern": "OUG80_ART13_A_DREPT_AUTOR",
        "nume_standard": get_nume_standard_din_json("OUG80_ART13_A_DREPT_AUTOR", "Acțiune privind drepturi de autor/conexe"),
        "articol_referinta": "Art. 13 lit. a)",
        "keywords": get_keywords("OUG80_ART13_A_DREPT_AUTOR"),
        "regula_calcul_id": "CALC_ART13_A",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Proprietate Intelectuală",
        "detalii_suplimentare": f"Taxă fixă {TAXA_100_LEI:,.2f} lei (pentru partea neevaluabilă).",
        "intrebari_ghidare": ["Litigiul vizează drepturi de autor sau conexe (neevaluabil în principal)?"],
    },
    "OUG80_ART13_B_BREVET": {
        "id_intern": "OUG80_ART13_B_BREVET",
        "nume_standard": get_nume_standard_din_json("OUG80_ART13_B_BREVET", "Acțiune privind drepturi izvorâte din brevet de invenție"),
        "articol_referinta": "Art. 13 lit. b)",
        "keywords": get_keywords("OUG80_ART13_B_BREVET"),
        "regula_calcul_id": "CALC_ART13_B",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Proprietate Intelectuală",
        "detalii_suplimentare": f"Taxă fixă {TAXA_100_LEI:,.2f} lei.",
        "intrebari_ghidare": ["Litigiul vizează drepturi dintr-un brevet de invenție?"],
    },
    "OUG80_ART13_C_MARCA_DESEN_NEVAL": {
        "id_intern": "OUG80_ART13_C_MARCA_DESEN_NEVAL",
        "nume_standard": get_nume_standard_din_json("OUG80_ART13_C_MARCA_DESEN_NEVAL", "Acțiune neevaluabilă marcă/desen/model industrial"),
        "articol_referinta": "Art. 13 lit. c)",
        "keywords": get_keywords("OUG80_ART13_C_MARCA_DESEN_NEVAL"),
        "regula_calcul_id": "CALC_ART13_C",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Proprietate Intelectuală",
        "detalii_suplimentare": f"Taxă fixă {TAXA_300_LEI:,.2f} lei (pentru componenta neevaluabilă).",
        "intrebari_ghidare": ["Litigiul vizează o marcă, desen sau model industrial și NU are caracter patrimonial?"],
    },
    "OUG80_ART14_1_INSOLVENTA": {
        "id_intern": "OUG80_ART14_1_INSOLVENTA",
        "nume_standard": get_nume_standard_din_json("OUG80_ART14_1_INSOLVENTA", "Cerere în materia insolvenței (deschidere procedură, etc.)"),
        "articol_referinta": "Art. 14(1)",
        "keywords": get_keywords("OUG80_ART14_1_INSOLVENTA"),
        "regula_calcul_id": "CALC_ART14_1",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Insolvență",
        "detalii_suplimentare": f"Taxă fixă {TAXA_200_LEI:,.2f} lei pentru cererile specifice procedurii insolvenței.",
        "intrebari_ghidare": ["Formulați o cerere în cadrul unei proceduri de insolvență (ex: cerere de deschidere, opoziție, contestație tabel)?", "NU include cereri de Apel/Recurs?"],
    },
    "OUG80_ART14_2_RC_INSTANTA": {
        "id_intern": "OUG80_ART14_2_RC_INSTANTA",
        "nume_standard": get_nume_standard_din_json("OUG80_ART14_2_RC_INSTANTA", "Cerere adresată instanței pentru Registrul Comerțului"),
        "articol_referinta": "Art. 14(2)",
        "keywords": get_keywords("OUG80_ART14_2_RC_INSTANTA"),
        "regula_calcul_id": "CALC_ART14_2",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Registrul Comerțului",
        "detalii_suplimentare": f"Taxă fixă {TAXA_100_LEI:,.2f} lei pentru cererile privind înregistrări în RC care sunt de competența instanței.",
        "intrebari_ghidare": ["Formulați o cerere adresată instanței privind înregistrări în Registrul Comerțului?"],
    },
    "OUG80_ART15_A_DIVORT_ACORD_CULPA_SEP": {
        "id_intern": "OUG80_ART15_A_DIVORT_ACORD_CULPA_SEP",
        "nume_standard": get_nume_standard_din_json("OUG80_ART15_A_DIVORT_ACORD_CULPA_SEP", "Divorț (Acord/Culpă/Separare > 2 ani)"),
        "articol_referinta": "Art. 15 lit. a)",
        "keywords": get_keywords("OUG80_ART15_A_DIVORT_ACORD_CULPA_SEP"),
        "regula_calcul_id": "CALC_ART15_A",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": "DIVORT",
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Familie",
        "detalii_suplimentare": f"Taxă fixă pentru divorț {TAXA_200_LEI:,.2f} lei. Cererile accesorii (nume, copii, locuință, etc.) sunt scutite (Art. 15(2)).",
        "intrebari_ghidare": ["Cerea dvs. principală este divorțul prin acord, din culpă sau bazat pe separarea în fapt de peste 2 ani?"],
    },
    "OUG80_ART15_B_DIVORT_CERERE_ACCEPTATA": {
        "id_intern": "OUG80_ART15_B_DIVORT_CERERE_ACCEPTATA",
        "nume_standard": get_nume_standard_din_json("OUG80_ART15_B_DIVORT_CERERE_ACCEPTATA", "Divorț (Cerere acceptată de pârât)"),
        "articol_referinta": "Art. 15 lit. b)",
        "keywords": get_keywords("OUG80_ART15_B_DIVORT_CERERE_ACCEPTATA"),
        "regula_calcul_id": "CALC_ART15_B",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": "DIVORT",
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Familie",
        "detalii_suplimentare": f"Taxă fixă pentru divorț {TAXA_50_LEI:,.2f} lei (când cererea unuia este acceptată de celălalt). Cererile accesorii sunt scutite.",
        "intrebari_ghidare": ["Cerea dvs. principală este divorțul la cererea unuia dintre soți, acceptată de celălalt?"],
    },
    "OUG80_ART15_C_DESPAGUB_PREST_COMP": {
        "id_intern": "OUG80_ART15_C_DESPAGUB_PREST_COMP",
        "nume_standard": get_nume_standard_din_json("OUG80_ART15_C_DESPAGUB_PREST_COMP", "Despăgubiri / Prestație compensatorie (în divorț)"),
        "articol_referinta": "Art. 15 lit. c)",
        "keywords": get_keywords("OUG80_ART15_C_DESPAGUB_PREST_COMP"),
        "regula_calcul_id": "CALC_ART15_C",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Familie",
        "detalii_suplimentare": f"Taxă fixă {TAXA_50_LEI:,.2f} lei (se taxează distinct de taxa de divorț).",
        "intrebari_ghidare": ["Solicitați despăgubiri sau prestație compensatorie în cadrul procesului de divorț?"],
    },
    "OUG80_ART15_D_NEACCESORIU_DIVORT": {
        "id_intern": "OUG80_ART15_D_NEACCESORIU_DIVORT",
        "nume_standard": get_nume_standard_din_json("OUG80_ART15_D_NEACCESORIU_DIVORT", "Cerere neaccesorie în divorț (ex: folosinta locuinței)"),
        "articol_referinta": "Art. 15 lit. d)",
        "keywords": get_keywords("OUG80_ART15_D_NEACCESORIU_DIVORT"),
        "regula_calcul_id": "CALC_SCUTIT",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "NU",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": ["OUG80_ART15_A_DIVORT_ACORD_CULPA_SEP", "OUG80_ART15_B_DIVORT_CERERE_ACCEPTATA"],
        "necesita_actiune_subiacenta": False,
        "categorie": "Familie",
        "detalii_suplimentare": "Aceste cereri (stabilire locuință copil, exercițiu autoritate, întreținere, nume, folosință locuință) sunt SCUTITE dacă sunt formulate în cadrul cererii de divorț (Art. 15(2)). Dacă sunt formulate SEPARAT, se taxează cu 20 lei cf. Art. 15 lit. e).",
        "intrebari_ghidare": ["Formulați una dintre aceste cereri (locuință copil, nume, întreținere etc.) ÎMPREUNĂ cu cererea de divorț?"],
    },
    "OUG80_ART15_E_FAMILIE_NEVAL": {
        "id_intern": "OUG80_ART15_E_FAMILIE_NEVAL",
        "nume_standard": get_nume_standard_din_json("OUG80_ART15_E_FAMILIE_NEVAL", "Altă cerere neevaluabilă în materie de familie"),
        "articol_referinta": "Art. 15 lit. e)",
        "keywords": get_keywords("OUG80_ART15_E_FAMILIE_NEVAL"),
        "regula_calcul_id": "CALC_ART15_E",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Familie",
        "detalii_suplimentare": f"Taxă fixă {TAXA_20_LEI:,.2f} lei pentru cererile neevaluabile din materia familiei, altele decât cele menționate specific (ex: tutela, curatela, punere sub interdicție, paternitate etc.).",
        "intrebari_ghidare": ["Formulați o cerere neevaluabilă în materie de familie, care nu este legată direct de divorț?"],
    },
    "OUG80_ART16_A_CONT_NEPATRIM": {
        "id_intern": "OUG80_ART16_A_CONT_NEPATRIM",
        "nume_standard": get_nume_standard_din_json("OUG80_ART16_A_CONT_NEPATRIM", "Contencios Adm: Anulare act / Recunoaștere drept / Obligare"),
        "articol_referinta": "Art. 16 lit. a)",
        "keywords": get_keywords("OUG80_ART16_A_CONT_NEPATRIM"),
        "regula_calcul_id": "CALC_ART16_A",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Contencios Administrativ",
        "detalii_suplimentare": f"Taxă fixă {TAXA_50_LEI:,.2f} lei.",
        "intrebari_ghidare": ["Cerea dvs. în contencios administrativ vizează anularea unui act, recunoașterea unui drept sau obligarea la eliberarea unui certificat/adeverințe și NU are caracter patrimonial?"],
    },
    "OUG80_ART16_B_CONT_PATRIM": {
        "id_intern": "OUG80_ART16_B_CONT_PATRIM",
        "nume_standard": get_nume_standard_din_json("OUG80_ART16_B_CONT_PATRIM", "Contencios Administrativ cu caracter patrimonial"),
        "articol_referinta": "Art. 16 lit. b)",
        "keywords": get_keywords("OUG80_ART16_B_CONT_PATRIM"),
        "regula_calcul_id": "CALC_ART16_B",
        "campuri_necesare": ["Valoare_Obiect"],
        "mod_determinare_valoare_implicit": "ART31_2_DECLARAT",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Contencios Administrativ",
        "detalii_suplimentare": f"Taxă 10% din valoare, dar nu mai mult de {CONT_ADM_PATRIM_PLAFON:,.0f} lei.",
        "intrebari_ghidare": ["Cerea dvs. în contencios administrativ vizează și obținerea unor despăgubiri materiale?", "Care este valoarea totală a despăgubirilor solicitate?"],
    },
    "OUG80_ART17_A_CONTEST_UNNPR": {
        "id_intern": "OUG80_ART17_A_CONTEST_UNNPR",
        "nume_standard": get_nume_standard_din_json("OUG80_ART17_A_CONTEST_UNNPR", "Contestație împotriva deciziilor Consiliului UNNPR"),
        "articol_referinta": "Art. 17 lit. a)",
        "keywords": get_keywords("OUG80_ART17_A_CONTEST_UNNPR"),
        "regula_calcul_id": "CALC_ART17_A",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Profesii Liberale",
        "detalii_suplimentare": f"Taxă fixă {TAXA_100_LEI:,.2f} lei.",
        "intrebari_ghidare": ["Formulați o contestație împotriva unei decizii a Consiliului Uniunii Naționale a Notarilor Publici?"],
    },
    "OUG80_ART17_B_PLANG_REFUZ_NOTAR": {
        "id_intern": "OUG80_ART17_B_PLANG_REFUZ_NOTAR",
        "nume_standard": get_nume_standard_din_json("OUG80_ART17_B_PLANG_REFUZ_NOTAR", "Plângere împotriva încheierii de respingere a cererii notariale"),
        "articol_referinta": "Art. 17 lit. b)",
        "keywords": get_keywords("OUG80_ART17_B_PLANG_REFUZ_NOTAR"),
        "regula_calcul_id": "CALC_ART17_B",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Profesii Liberale",
        "detalii_suplimentare": f"Taxă fixă {TAXA_20_LEI:,.2f} lei.",
        "intrebari_ghidare": ["Formulați o plângere împotriva încheierii notarului de respingere a cererii de îndeplinire a unui act notarial?"],
    },
    "OUG80_ART18_EXEC_JUD": {
        "id_intern": "OUG80_ART18_EXEC_JUD",
        "nume_standard": get_nume_standard_din_json("OUG80_ART18_EXEC_JUD", "Cereri privind Executorii Judecătorești (Conflict Comp./Plângere Refuz/Supralegalizare)"),
        "articol_referinta": "Art. 18",
        "keywords": get_keywords("OUG80_ART18_EXEC_JUD"),
        "regula_calcul_id": "CALC_ART18",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Executare",
        "detalii_suplimentare": f"Taxă fixă {TAXA_20_LEI:,.2f} lei pentru cereri privind conflicte de competență, plângeri la refuzul executorului, supralegalizare semnătură/sigiliu executor.",
        "intrebari_ghidare": ["Formulați o cerere referitoare la executori judecătorești (conflict competență, plângere refuz, supralegalizare)?"],
    },
    "OUG80_ART19_CONTRAVENTIE": {
        "id_intern": "OUG80_ART19_CONTRAVENTIE",
        "nume_standard": get_nume_standard_din_json("OUG80_ART19_CONTRAVENTIE", "Plângere Contravențională / Cale de atac"),
        "articol_referinta": "Art. 19",
        "keywords": get_keywords("OUG80_ART19_CONTRAVENTIE"),
        "regula_calcul_id": "CALC_ART19",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Contravențional",
        "detalii_suplimentare": f"Taxă fixă {TAXA_20_LEI:,.2f} lei.",
        "intrebari_ghidare": ["Formulați o plângere împotriva unui proces-verbal de contravenție sau o cale de atac în materie contravențională?"],
    },
    "OUG80_ART20_CF_FARA_FOND": {
        "id_intern": "OUG80_ART20_CF_FARA_FOND",
        "nume_standard": get_nume_standard_din_json("OUG80_ART20_CF_FARA_FOND", "Cerere Carte Funciară (care NU vizează fondul)"),
        "articol_referinta": "Art. 20",
        "keywords": get_keywords("OUG80_ART20_CF_FARA_FOND"),
        "regula_calcul_id": "CALC_ART20",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Carte Funciară",
        "detalii_suplimentare": f"Taxă fixă {TAXA_50_LEI:,.2f} lei pentru plângeri împotriva încheierilor CF, cereri de reexaminare, etc., care nu vizează fondul dreptului (acțiunile de fond, ex: rectificare CF, se taxează conform Art. 3 sau altor reguli).",
        "intrebari_ghidare": ["Formulați o plângere împotriva unei încheieri de Carte Funciară sau o cerere de reexaminare?"],
    },
    "OUG80_ART21_ASOC_PROP": {
        "id_intern": "OUG80_ART21_ASOC_PROP",
        "nume_standard": get_nume_standard_din_json("OUG80_ART21_ASOC_PROP", "Cereri Asociații Proprietari (Înregistrare/Apel încheiere)"),
        "articol_referinta": "Art. 21",
        "keywords": get_keywords("OUG80_ART21_ASOC_PROP"),
        "regula_calcul_id": "CALC_ART21",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Asociații Proprietari",
        "detalii_suplimentare": f"Taxă fixă {TAXA_20_LEI:,.2f} lei pentru cereri de înregistrare asociație sau apel împotriva încheierii judecătorului delegat.",
        "intrebari_ghidare": ["Formulați o cerere de înregistrare a unei asociații de proprietari sau un apel la încheierea judecătorului delegat?"],
    },
    "OUG80_ART22_A_SUPRALEGALIZARE": {
        "id_intern": "OUG80_ART22_A_SUPRALEGALIZARE",
        "nume_standard": get_nume_standard_din_json("OUG80_ART22_A_SUPRALEGALIZARE", "Supralegalizare sigiliu/semnătură (Minister Justiție)"),
        "articol_referinta": "Art. 22 lit. a)",
        "keywords": get_keywords("OUG80_ART22_A_SUPRALEGALIZARE"),
        "regula_calcul_id": "CALC_ART22_A",
        "campuri_necesare": ["Numar_Inscrise_Supralegalizare"],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Cereri Diverse",
        "detalii_suplimentare": f"Taxă {TAXA_SUPRALEGALIZARE_MJ_INSCRIS:,.2f} lei per înscris.",
        "intrebari_ghidare": ["Solicitați supralegalizarea sigiliului/semnăturii de către Ministerul Justiției?", "Pentru câte înscrisuri?"],
    },
    "OUG80_ART22_B_AUTORIZ_TRAD": {
        "id_intern": "OUG80_ART22_B_AUTORIZ_TRAD",
        "nume_standard": get_nume_standard_din_json("OUG80_ART22_B_AUTORIZ_TRAD", "Autorizare/Reautorizare Traducători/Interpreți"),
        "articol_referinta": "Art. 22 lit. b)",
        "keywords": get_keywords("OUG80_ART22_B_AUTORIZ_TRAD"),
        "regula_calcul_id": "CALC_ART22_B",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Profesii Liberale",
        "detalii_suplimentare": f"Taxă fixă {TAXA_300_LEI:,.2f} lei.",
        "intrebari_ghidare": ["Solicitați autorizarea sau reautorizarea ca traducător/interpret de către Ministerul Justiției?"],
    },
    "OUG80_ART22_C_ATESTARE_CALIF": {
        "id_intern": "OUG80_ART22_C_ATESTARE_CALIF",
        "nume_standard": get_nume_standard_din_json("OUG80_ART22_C_ATESTARE_CALIF", "Atestare calificare profesională (UE/SEE)"),
        "articol_referinta": "Art. 22 lit. c)",
        "keywords": get_keywords("OUG80_ART22_C_ATESTARE_CALIF"),
        "regula_calcul_id": "CALC_ART22_C",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Profesii Liberale",
        "detalii_suplimentare": f"Taxă fixă {TAXA_100_LEI:,.2f} lei.",
        "intrebari_ghidare": ["Solicitați atestarea de către Ministerul Justiției a calificării profesionale obținute în România (pt recunoaștere UE/SEE)?"],
    },
    "OUG80_ART22_D_RECUN_CALIF": {
        "id_intern": "OUG80_ART22_D_RECUN_CALIF",
        "nume_standard": get_nume_standard_din_json("OUG80_ART22_D_RECUN_CALIF", "Recunoaștere calificare profesională (UE/SEE)"),
        "articol_referinta": "Art. 22 lit. d)",
        "keywords": get_keywords("OUG80_ART22_D_RECUN_CALIF"),
        "regula_calcul_id": "CALC_ART22_D",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Profesii Liberale",
        "detalii_suplimentare": f"Taxă fixă {TAXA_100_LEI:,.2f} lei.",
        "intrebari_ghidare": ["Solicitați recunoașterea de către Ministerul Justiției a calificării profesionale obținute într-un stat UE/SEE?"],
    },
    "APEL_GENERAL": {
        "id_intern": "APEL_GENERAL",
        "nume_standard": get_nume_standard_din_json("APEL_GENERAL", "Apel (Regulă Generală)"),
        "articol_referinta": "Art. 23",
        "keywords": get_keywords("APEL_GENERAL"),
        "regula_calcul_id": "CALC_APEL_GENERAL",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Căi de Atac",
        "detalii_suplimentare": f"Taxa este 50% din taxa achitată în primă instanță (cu excepțiile prevăzute), dar nu mai puțin de {TAXA_20_LEI:,.2f} lei.",
        "intrebari_ghidare": ["Declarați apel împotriva unei hotărâri?", "Introduceți taxa achitată în primă instanță în secțiunea 'Date Generale'."]
    },
    "RECURS_GENERAL": {
        "id_intern": "RECURS_GENERAL",
        "nume_standard": get_nume_standard_din_json("RECURS_GENERAL", "Recurs (Regulă Generală)"),
        "articol_referinta": "Art. 24",
        "keywords": get_keywords("RECURS_GENERAL"),
        "regula_calcul_id": "CALC_RECURS_GENERAL",
        "campuri_necesare": [
            "Este_Evaluabil",
            "Motive_Recurs_Invocate",
            "Valoare_Contestata_Recurs"
        ],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Căi de Atac",
        "detalii_suplimentare": f"Motive procedurale (Art. 488(1) pct. 1-7): {TAXA_100_LEI:,.2f} lei.\nMotive substanțiale (Art. 488(1) pct. 8): Neevaluabil: {TAXA_100_LEI:,.2f} lei; Evaluabil: 50% din taxa calculată la valoarea contestată, minim {TAXA_100_LEI:,.2f} lei.",
        "intrebari_ghidare": ["Declarați recurs împotriva unei hotărâri?", "Ce motive invocați (procedurale/substanțiale)?", "Dacă invocați motive substanțiale, recursul este evaluabil?", "Dacă da, care este valoarea contestată în recurs?"]
    },
    "OUG80_ART25_1_APEL_RECURS_SPECIFIC_20": {
        "id_intern": "OUG80_ART25_1_APEL_RECURS_SPECIFIC_20",
        "nume_standard": get_nume_standard_din_json("OUG80_ART25_1_APEL_RECURS_SPECIFIC_20", "Apel/Recurs specific (Taxă 20 lei)"),
        "articol_referinta": "Art. 25(1)",
        "keywords": get_keywords("OUG80_ART25_1_APEL_RECURS_SPECIFIC_20"),
        "regula_calcul_id": "CALC_ART25_1",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Căi de Atac",
        "detalii_suplimentare": f"Taxă fixă {TAXA_20_LEI:,.2f} lei pentru apel/recurs împotriva încheierilor specifice (ex: suspendare judecată, taxe timbru, amenzi, etc.).",
        "intrebari_ghidare": ["Declarați apel/recurs împotriva unei încheieri care se taxează cu 20 lei conform Art. 25(1)?"],
    },
    "OUG80_ART25_2_APEL_RECURS_SPECIFIC_50": {
        "id_intern": "OUG80_ART25_2_APEL_RECURS_SPECIFIC_50",
        "nume_standard": get_nume_standard_din_json("OUG80_ART25_2_APEL_RECURS_SPECIFIC_50", "Apel/Recurs specific (Taxă 50 lei)"),
        "articol_referinta": "Art. 25(2)",
        "keywords": get_keywords("OUG80_ART25_2_APEL_RECURS_SPECIFIC_50"),
        "regula_calcul_id": "CALC_ART25_2",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Căi de Atac",
        "detalii_suplimentare": f"Taxă fixă {TAXA_50_LEI:,.2f} lei pentru apel/recurs împotriva încheierilor specifice (ex: măsuri asigurătorii, competență, etc.).",
        "intrebari_ghidare": ["Declarați apel/recurs împotriva unei încheieri care se taxează cu 50 lei conform Art. 25(2)?"],
    },
    "OUG80_ART25_3_APEL_RECURS_CONSIDERENTE": {
        "id_intern": "OUG80_ART25_3_APEL_RECURS_CONSIDERENTE",
        "nume_standard": get_nume_standard_din_json("OUG80_ART25_3_APEL_RECURS_CONSIDERENTE", "Apel/Recurs DOAR pe considerente"),
        "articol_referinta": "Art. 25(3)",
        "keywords": get_keywords("OUG80_ART25_3_APEL_RECURS_CONSIDERENTE"),
        "regula_calcul_id": "CALC_ART25_3",
        "campuri_necesare": ["Este_Cale_Atac_Doar_Considerente"],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Căi de Atac",
        "detalii_suplimentare": f"Taxă fixă {TAXA_100_LEI:,.2f} lei.",
        "intrebari_ghidare": ["Calea de atac formulată vizează EXCLUSIV considerentele hotărârii atacate?"],
    },
    "OUG80_ART26_1_CONTESTATIE_ANULARE": {
        "id_intern": "OUG80_ART26_1_CONTESTATIE_ANULARE",
        "nume_standard": get_nume_standard_din_json("OUG80_ART26_1_CONTESTATIE_ANULARE", "Contestație în Anulare"),
        "articol_referinta": "Art. 26(1)",
        "keywords": get_keywords("OUG80_ART26_1_CONTESTATIE_ANULARE"),
        "regula_calcul_id": "CALC_ART26_1",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Căi de Atac",
        "detalii_suplimentare": f"Taxă fixă {TAXA_100_LEI:,.2f} lei.",
        "intrebari_ghidare": ["Formulați o contestație în anulare?"],
    },
    "OUG80_ART26_2_REVIZUIRE": {
        "id_intern": "OUG80_ART26_2_REVIZUIRE",
        "nume_standard": get_nume_standard_din_json("OUG80_ART26_2_REVIZUIRE", "Revizuire"),
        "articol_referinta": "Art. 26(2)",
        "keywords": get_keywords("OUG80_ART26_2_REVIZUIRE"),
        "regula_calcul_id": "CALC_ART26_2",
        "campuri_necesare": ["Numar_Motive_Revizuire"],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Căi de Atac",
        "detalii_suplimentare": f"Taxă {TAXA_100_LEI:,.2f} lei pentru fiecare motiv de revizuire invocat.",
        "intrebari_ghidare": ["Formulați o cerere de revizuire?", "Câte motive de revizuire invocați?"],
    },
    "OUG80_ART26_3_ANULARE_ARBITRAJ": {
        "id_intern": "OUG80_ART26_3_ANULARE_ARBITRAJ",
        "nume_standard": get_nume_standard_din_json("OUG80_ART26_3_ANULARE_ARBITRAJ", "Acțiune în anulare hotărâre arbitrală"),
        "articol_referinta": "Art. 26(3)",
        "keywords": get_keywords("OUG80_ART26_3_ANULARE_ARBITRAJ"),
        "regula_calcul_id": "CALC_ART26_3",
        "campuri_necesare": ["Numar_Motive_Anulare_Arbitraj"],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Arbitraj",
        "detalii_suplimentare": f"Taxă {TAXA_100_LEI:,.2f} lei pentru fiecare motiv de nulitate invocat. Recursul se taxează separat.",
        "intrebari_ghidare": ["Formulați o acțiune în anularea unei hotărâri arbitrale?", "Câte motive de nulitate invocați?"],
    },
    "OUG80_ART27_NEVAL_GENERAL": {
        "id_intern": "OUG80_ART27_NEVAL_GENERAL",
        "nume_standard": get_nume_standard_din_json("OUG80_ART27_NEVAL_GENERAL", "Altă cerere neevaluabilă (Regulă Generală)"),
        "articol_referinta": "Art. 27",
        "keywords": get_keywords("OUG80_ART27_NEVAL_GENERAL"),
        "regula_calcul_id": "CALC_ART27",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Nepatrimonial",
        "detalii_suplimentare": f"Taxă fixă {TAXA_20_LEI:,.2f} lei pentru orice altă cerere neevaluabilă în bani pentru care nu este prevăzută o taxă specifică.",
        "intrebari_ghidare": ["Formulați o cerere neevaluabilă în bani care nu se încadrează în niciuna dintre categoriile anterioare?"],
    },
    "OUG80_REVEND_IMOBIL": {
        "id_intern": "OUG80_REVEND_IMOBIL",
        "nume_standard": get_nume_standard_din_json("OUG80_REVEND_IMOBIL", "Revendicare Imobiliară"),
        "articol_referinta": "Art. 3(1) rap. la Art. 31(3)",
        "keywords": get_keywords("OUG80_REVEND_IMOBIL"),
        "regula_calcul_id": "CALC_REVEND_IMOBIL",
        "campuri_necesare": ["Valoare_Bun_Imobil"],
        "mod_determinare_valoare_implicit": "ART31_3_IMPOZABIL",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Patrimonial",
        "detalii_suplimentare": "Taxa se calculează conform Art. 3(1) la valoarea impozabilă a imobilului conform Art. 31(3).",
        "intrebari_ghidare": ["Solicitați restituirea unui bun imobil (teren/clădire)?", "Care este valoarea impozabilă/grilă notarială a acestuia?"],
    },
    "OUG80_REVEND_MOBIL": {
        "id_intern": "OUG80_REVEND_MOBIL",
        "nume_standard": get_nume_standard_din_json("OUG80_REVEND_MOBIL", "Revendicare Mobiliară"),
        "articol_referinta": "Art. 3(1) rap. la Art. 31(2)",
        "keywords": get_keywords("OUG80_REVEND_MOBIL"),
        "regula_calcul_id": "CALC_REVEND_MOBIL",
        "campuri_necesare": ["Valoare_Obiect"],
        "mod_determinare_valoare_implicit": "ART31_2_DECLARAT",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Patrimonial",
        "detalii_suplimentare": "Taxa se calculează conform Art. 3(1) la valoarea declarată a bunului mobil.",
        "intrebari_ghidare": ["Solicitați restituirea unui bun mobil?", "Care este valoarea declarată a acestuia?"],
    },
    "OUG80_DESF_CONST_PROPR": {
        "id_intern": "OUG80_DESF_CONST_PROPR",
        "nume_standard": get_nume_standard_din_json("OUG80_DESF_CONST_PROPR", "Desființare Construcție (Proprietar Teren)"),
        "articol_referinta": "Art. 3(1) rap. la Art. 31(2)",
        "keywords": get_keywords("OUG80_DESF_CONST_PROPR"),
        "regula_calcul_id": "CALC_DESF_CONST_PROPR",
        "campuri_necesare": ["Valoare_Bun_Imobil"],
        "mod_determinare_valoare_implicit": "ART31_2_TEREN_AFECTAT",
        "taxare_separata_implicit": "NU",
        "grup_exceptie_insumare": "DESF_REVEND_IDENTIC",
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Patrimonial",
        "detalii_suplimentare": "Taxa se calculează conform Art. 3(1) la valoarea terenului afectat. Dacă se cere ȘI revendicarea terenului (OUG80_REVEND_IMOBIL), se plătește doar taxa de revendicare.",
        "intrebari_ghidare": ["Solicitați desființarea unei construcții aflate pe terenul dvs.?", "Care este valoarea terenului pe care se află construcția?", "Solicitați și revendicarea terenului?"],
    },
    "OUG80_PREDARE_PERS": {
        "id_intern": "OUG80_PREDARE_PERS",
        "nume_standard": get_nume_standard_din_json("OUG80_PREDARE_PERS", "Predare Bun (Acțiune Personală)"),
        "articol_referinta": "Art. 3(1) rap. la Art. 31(2)",
        "keywords": get_keywords("OUG80_PREDARE_PERS"),
        "regula_calcul_id": "CALC_PREDARE_PERS",
        "campuri_necesare": ["Valoare_Obiect"],
        "mod_determinare_valoare_implicit": "ART31_2_DECLARAT",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Patrimonial",
        "detalii_suplimentare": "Taxa se calculează conform Art. 3(1) la valoarea declarată a bunului (dacă izvorăște dintr-un raport obligațional).",
        "intrebari_ghidare": ["Solicitați predarea unui bun în baza unui contract/obligații?", "Care este valoarea declarată a bunului?"],
    },
    "OUG80_PREDARE_REALA_IMOBIL": {
        "id_intern": "OUG80_PREDARE_REALA_IMOBIL",
        "nume_standard": get_nume_standard_din_json("OUG80_PREDARE_REALA_IMOBIL", "Predare Bun Imobil (Acțiune Reală)"),
        "articol_referinta": "Art. 3(1) rap. la Art. 31(3)",
        "keywords": get_keywords("OUG80_PREDARE_REALA_IMOBIL"),
        "regula_calcul_id": "CALC_PREDARE_REALA_IMOBIL",
        "campuri_necesare": ["Valoare_Bun_Imobil"],
        "mod_determinare_valoare_implicit": "ART31_3_IMPOZABIL",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Patrimonial",
        "detalii_suplimentare": "Taxa se calculează conform Art. 3(1) la valoarea impozabilă a imobilului (dacă se întemeiază pe un drept real).",
        "intrebari_ghidare": ["Solicitați predarea unui bun imobil în baza unui drept real (proprietate, etc.)?", "Care este valoarea impozabilă/grilă notarială a imobilului?"],
    },
    "OUG80_PREDARE_REALA_MOBIL": {
        "id_intern": "OUG80_PREDARE_REALA_MOBIL",
        "nume_standard": get_nume_standard_din_json("OUG80_PREDARE_REALA_MOBIL", "Predare Bun Mobil (Acțiune Reală)"),
        "articol_referinta": "Art. 3(1) rap. la Art. 31(2)",
        "keywords": get_keywords("OUG80_PREDARE_REALA_MOBIL"),
        "regula_calcul_id": "CALC_PREDARE_REALA_MOBIL",
        "campuri_necesare": ["Valoare_Obiect"],
        "mod_determinare_valoare_implicit": "ART31_2_DECLARAT",
        "taxare_separata_implicit": "DA",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Patrimonial",
        "detalii_suplimentare": "Taxa se calculează conform Art. 3(1) la valoarea declarată a bunului mobil (dacă se întemeiază pe un drept real).",
        "intrebari_ghidare": ["Solicitați predarea unui bun mobil în baza unui drept real?", "Care este valoarea declarată a bunului?"],
    },
    "CAZ_SCUTIT_EXPLICIT": {
        "id_intern": "CAZ_SCUTIT_EXPLICIT",
        "nume_standard": get_nume_standard_din_json("CAZ_SCUTIT_EXPLICIT", "Cerere Scutită Explicit (Lege Specială/Alt Art.)"),
        "articol_referinta": "Diverse",
        "keywords": get_keywords("CAZ_SCUTIT_EXPLICIT"),
        "regula_calcul_id": "CALC_SCUTIT",
        "campuri_necesare": [],
        "mod_determinare_valoare_implicit": "Neevaluabil",
        "taxare_separata_implicit": "NU",
        "grup_exceptie_insumare": None,
        "este_accesoriu_scutit_la": None,
        "necesita_actiune_subiacenta": False,
        "categorie": "Scutiri",
        "detalii_suplimentare": "Pentru cererile scutite explicit prin alte articole din OUG 80/2013 sau legi speciale (ex: protecția consumatorilor, minori, dizabilități - conform Art. 29).",
        "intrebari_ghidare": ["Cerea dvs. este scutită explicit de taxă printr-o prevedere legală specifică?"],
    },
}
# ============================================
# Validare internă la încărcare (opțional)
# ============================================
def valideaza_tipuri_cereri():
    """Verifică dacă structura TIPURI_CERERI este consistentă."""
    erori = []
    reguli_existente = set() # Acest set va stoca ID-urile regulilor de calcul întâlnite

    if not isinstance(TIPURI_CERERI, dict):
        return ["TIPURI_CERERI nu este un dicționar."]

    for id_intern_cheie, detalii in TIPURI_CERERI.items():
        if not isinstance(detalii, dict):
            erori.append(f"Intrarea pentru '{id_intern_cheie}' nu este dicționar.")
            continue # Treci la următoarea intrare dacă aceasta nu e dicționar

        # Verifică corespondența id_intern
        id_intern_valoare = detalii.get("id_intern")
        if id_intern_valoare != id_intern_cheie:
            erori.append(f"Cheia '{id_intern_cheie}' nu corespunde cu 'id_intern' din detalii: '{id_intern_valoare}'")

        # Verifică prezența și tipul câmpurilor obligatorii
        campuri_obligatorii = {
            "nume_standard": str,
            "articol_referinta": str,
            "keywords": list,
            "regula_calcul_id": str,
            "campuri_necesare": list,
            "mod_determinare_valoare_implicit": str,
            "taxare_separata_implicit": str, # Ar trebui să fie "DA" sau "NU"
            # "grup_exceptie_insumare": (str, type(None)), # Poate fi string sau None
            "este_accesoriu_scutit_la": (list, type(None)), # Poate fi listă sau None
            "necesita_actiune_subiacenta": bool,
            "categorie": str,
            "detalii_suplimentare": str,
            "intrebari_ghidare": list
        }

        for camp, tip_asteptat in campuri_obligatorii.items():
            if camp not in detalii:
                erori.append(f"Lipsă câmp obligatoriu '{camp}' pentru '{id_intern_cheie}'.")
            else:
                # Verificare tip, cu excepții pentru câmpurile care pot fi None
                if camp == "grup_exceptie_insumare":
                    if not (isinstance(detalii[camp], str) or detalii[camp] is None):
                        erori.append(f"Câmpul '{camp}' pentru '{id_intern_cheie}' trebuie să fie string sau None, dar este {type(detalii[camp])}.")
                elif camp == "este_accesoriu_scutit_la":
                    if not (isinstance(detalii[camp], list) or detalii[camp] is None):
                         erori.append(f"Câmpul '{camp}' pentru '{id_intern_cheie}' trebuie să fie listă sau None, dar este {type(detalii[camp])}.")
                elif not isinstance(detalii[camp], tip_asteptat):
                    erori.append(f"Câmpul '{camp}' pentru '{id_intern_cheie}' are tipul {type(detalii[camp])}, așteptat {tip_asteptat}.")

        # Adaugă regula de calcul la set pentru verificări ulterioare dacă e necesar
        if "regula_calcul_id" in detalii and isinstance(detalii["regula_calcul_id"], str):
            reguli_existente.add(detalii["regula_calcul_id"])

        # Validare specifică pentru keywords (similar cu înainte)
        if "keywords" in detalii and isinstance(detalii["keywords"], list):
            if not detalii["keywords"] and taxa_timbru_keywords.get(id_intern_cheie) is not None:
                 logger.warning(f"Lista 'keywords' pentru '{id_intern_cheie}' este goală în cod, deși a fost găsită în JSON (taxaTimbruKeywords). Verificați.")
        elif "keywords" in detalii: # există dar nu e listă (deja prins mai sus, dar dublăm pt claritate)
             erori.append(f"'keywords' pentru '{id_intern_cheie}' nu este listă.")
        else: # nu există (deja prins mai sus)
            pass


    # Aici se pot adăuga verificări suplimentare, ex: dacă toate regulile definite în
    # taxa_timbru_logic.py (dacă s-ar importa) au corespondent în `reguli_existente`.
    # Momentan, validarea se concentrează pe structura internă a TIPURI_CERERI.

    return erori

# Rulează validarea la importul modulului
erori_validare = valideaza_tipuri_cereri()
if erori_validare:
    logger.error("!!! Erori de validare detectate în structura TIPURI_CERERI din taxa_timbru_data.py !!!")
    for eroare in erori_validare:
        logger.error(f"  - {eroare}")
else:
    logger.info("Structura TIPURI_CERERI din taxa_timbru_data.py a fost validată cu succes.")


# --- SFÂRȘITUL FIȘIERULUI taxa_timbru_data.py ---
